# Generated by Django 2.2 on 2020-10-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201003_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='summary',
            field=models.CharField(default="It's simply awesome", max_length=300),
            preserve_default=False,
        ),
    ]
