# Generated by Django 2.2 on 2020-10-17 15:32

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='body',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
